version: '3.5'

services:
  raft:
    image: raft
    expose:
      - "${RPC_PORT}"
      - "${SERVICE_PORT}"
      - "${GATEWAY_PORT}"
    networks:
      - raft
    deploy:
      replicas: 4
    env_file:
      - .env

networks:
  raft:
    external: true
