version: '3.5'

services:
  raft:
    image: raft
    expose:
      - "${RPC_PORT}"
      - "${SERVICE_PORT}"
      - "${GATEWAY_PORT}"
    networks:
      - raft
    #deploy:
    #  replicas: 4
    env_file:
      - .env
    volumes:
      - /gluster:/log:rw,shared
    depends_on:
      - gluster

  gluster:
    image: gluster
    privileged: true
    environment:
      - NET_IFACE=eth0
    networks:
      - raft
    volumes:
      - /gluster:/log:rw,shared

networks:
  raft:
    external: true
#services:
#  raft:
#    image: raft
#    #expose:
#    #  - "${RPC_PORT}"
#    #  - "${SERVICE_PORT}"
#    #  - "${GATEWAY_PORT}"
#    network_mode: host
#    environment:
#      - NET_IFACE=ens33
#    env_file:
#      - .env
#
#  gluster:
#    image: gluster
#    network_mode: host
#    environment:
#      - NET_IFACE=ens33